const main = async () => {
  console.log("main")
}

main().catch(e => console.log("Internal Server Error:", e))
